version: "3.1"

services:
  db:
    image: postgres:15.0-alpine
    container_name: voting-session-manager-db
    restart: always
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: application
      POSTGRES_DB: voting-session-manager
    ports:
      - "5432:5432"

  adminer:
    image: adminer:4.8.1
    container_name: voting-session-manager-adminer
    restart: always
    ports:
      - "8082:8080"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    container_name: voting-session-manager-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-broker:
    image: confluentinc/cp-kafka:7.2.2
    container_name: voting-session-manager-kafka-broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.4.0
    container_name: voting-session-manager-kafka-ui
    ports:
      - "8083:8083"
    restart: always
    depends_on:
      - zookeeper
      - kafka-broker
    environment:
      - SERVER_PORT=8083
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-broker:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181
