server.port: 8081
spring:
  jpa:
    hibernate.ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/voting-session-manager
    username: application
    password: application

springdoc.api-docs.groups.enabled: true

lombok.nonNull.exceptionType: IllegalArgumentException